### ISSUE TITLE
LUA errors when blocking spam and reporting it

### ISSUE THREAD

**Issue by Nillx** [funkydude/BadBoy#95] opened 2018-07-28 13:24 UTC
**Error when blocking something:**
```
2x BadBoy\BadBoy-v8.0.7.lua:217: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))
[C]: ?
BadBoy\BadBoy-v8.0.7.lua:217: in function <BadBoy\BadBoy.lua:214>
BadBoy\BadBoy-v8.0.7.lua:236: in function <BadBoy\BadBoy.lua:233>
[C]: in function `Show'
BadBoy\BadBoy-v8.0.7.lua:174: in function <BadBoy\BadBoy.lua:78>

Locals:
(*temporary) = <table> {
 IsBattleNetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:63
 SetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:47
 IsCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:129
 IsBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:99
 SetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:71
 IsGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:59
 chatLineID = 1605
 IsChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:87
 Clear = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:144
 IsValid = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:51
 SetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:107
 IsVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:113
 GetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:103
 IsUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:75
 SetCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:133
 GetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:117
 IsCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:139
 GetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:91
 ClearAndSetField = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:158
 GetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:67
 GetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:79
 SetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:83
 SetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:95
 SetCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:121
}
```

**This is the error i get when i report someone:**

```
2x BadBoy\BadBoy-v8.0.7.lua:284: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))
[C]: ?
BadBoy\BadBoy-v8.0.7.lua:284: in function <BadBoy\BadBoy.lua:258>

Locals:
(*temporary) = <table> {
 IsBattleNetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:63
 SetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:47
 IsCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:129
 IsBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:99
 SetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:71
 IsGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:59
 chatLineID = 1605
 IsChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:87
 Clear = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:144
 IsValid = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:51
 SetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:107
 IsVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:113
 GetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:103
 IsUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:75
 SetCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:133
 GetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:117
 IsCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:139
 GetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:91
 ClearAndSetField = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:158
 GetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:67
 GetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:79
 SetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:83
 SetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:95
 SetCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:121
}
```

**Comment by Sixthly** [comment] 2018-08-01 08:42
`2x BadBoy\BadBoy-v8.0.7.lua:217: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))`

I've been seeing this a lot since the BfA pre-patch, too.

**Comment by Sixthly** [comment] 2018-08-01 08:55
```
Message: Interface\AddOns\BadBoy\BadBoy.lua:217: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))
Time: Wed Aug  1 18:53:38 2018
Count: 9
Stack: Interface\AddOns\BadBoy\BadBoy.lua:217: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))
[C]: ?
Interface\AddOns\BadBoy\BadBoy.lua:217: in function <Interface\AddOns\BadBoy\BadBoy.lua:214>
Interface\AddOns\BadBoy\BadBoy.lua:236: in function <Interface\AddOns\BadBoy\BadBoy.lua:233>
(tail call): ?
[C]: in function `Show'
Interface\AddOns\BadBoy\BadBoy.lua:174: in function <Interface\AddOns\BadBoy\BadBoy.lua:78>

Locals: (*temporary) = <table> {
 IsBattleNetGUID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:63
 SetGUID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:47
 IsCommunityData = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:129
 IsBattlefieldScoreIndex = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:99
 SetUnit = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:71
 IsGUID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:59
 chatLineID = 575
 IsChatLineID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:87
 Clear = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:144
 IsValid = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:51
 SetVoiceID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:107
 IsVoiceID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:113
 GetBattlefieldScoreIndex = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:103
 IsUnit = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:75
 SetCommunityInvitation = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:133
 GetVoiceID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:117
 IsCommunityInvitation = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:139
 GetChatLineID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:91
 ClearAndSetField = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:158
 GetGUID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:67
 GetUnit = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:79
 SetChatLineID = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:83
 SetBattlefieldScoreIndex = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:95
 SetCommunityData = <function> defined @Interface\FrameXML\ObjectAPI\PlayerLocation.lua:121
}
```

**Comment by funkydude** [comment] 2018-08-01 12:43
Cannot reproduce this. Does it happen with only BadBoy enabled?

**Comment by Nillx** [comment] 2018-08-01 13:55
Im no longer getting that error since i made the original post. Im not sure what was causing it.

**Comment by Sixthly** [comment] 2018-09-01 03:01
I still get the errors, but they are so infrequent that it's not viable for me to disable all of my UI for the off-chance it happens within a week.

**Comment by tyates** [comment] 2018-09-02 20:42
I get this consistently, literally cannot right click on any in-game name. Not sure if it's a conflict with something else, will try to figure it out.

**Comment by MysticalOS** [comment] 2018-10-21 18:42
The error pretty much only occurs at entering world. you basically login to game. badboy throws 1-2 of these errors then doesn't throw them again. I don't load into world slowly either, using an NVMe drive and very few addons, I pop into game in seconds. I can repro this pretty much 100x of time though. Login, throws couple errors, then behaves rest of session.

**Comment by funkydude** [comment] 2018-10-21 18:49
So it happens within 10 seconds of the loading screen turning off?

What if you type /reload as soon as you can after logging on?

**Comment by MysticalOS** [comment] 2018-10-23 00:58
Does happen on reload. in fact it also appears to happen well after login too. just afking in boralus long enough on stormrage-US and error will start to happen even 30+ min after login, so i was wrong about it being login only. Maybe one of those annoying things where the player who spammed already logged off when api is called?

**Comment by funkydude** [comment] 2018-10-23 15:51
@MysticalOS I added a bunch of chat prints in the latest version. Can you confirm you are still getting errors but seeing 0 chat prints?

**Comment by MysticalOS** [comment] 2018-10-30 04:48
It took many days for another error to pop up.

I didn't see any chat prints though

1x BadBoy\BadBoy-v8.0.13.lua:238: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))
[C]: ?
BadBoy\BadBoy-v8.0.13.lua:238: in function <BadBoy\BadBoy.lua:232>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = <table> {
 IsBattleNetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:63
 SetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:47
 IsCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:129
 IsBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:99
 SetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:71
 IsGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:59
 chatLineID = 152
 IsChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:87
 Clear = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:144
 IsValid = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:51
 SetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:107
 IsVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:113
 GetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:103
 IsUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:75
 SetCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:133
 GetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:117
 IsCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:139
 GetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:91
 ClearAndSetField = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:158
 GetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:67
 GetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:79
 SetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:83
 SetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:95
 SetCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:121
}

with version 8.0.13

**Comment by funkydude** [comment] 2018-12-12 14:32
Since it is now 8.1 I shall close this. If it happens again, please re-open and post the error.

**Closed by funkydude** 2018-12-12 14:32 UTC
