### ISSUE TITLE
LUA errors when reporting spam (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))

### ISSUE THREAD

**Issue by Yinepuhotep** [funkydude/BadBoy#99] opened 2018-08-23 00:35 UTC
Date: 2018-08-22 20:29:10
ID: 30
Error occured in: Global
Count: 1
Message: ..\AddOns\BadBoy\BadBoy.lua line 284:
   bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:613:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:575
   [C]: ?
   [C]: ?
   BadBoy\BadBoy.lua:284:
      BadBoy\BadBoy.lua:258
Locals:
errMsg = "Interface\AddOns\BadBoy\BadBoy.lua:284: bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ChatInfo.CanReportPlayer(playerLocation))"
errorTime = 36389417.694438
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:379
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:106
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:585
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:356
 SantizeErrorReportString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:387
 errorFrame = <unnamed> {
 }
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  WowheadLooter, v80000
  Ace3, v
  Altoholic, vr189
  ArtifactButton, v6.0
  Atlas, vv1.44.03
  AtlasArena, vv1.07.02
  AtlasBattlegrounds, vv1.44.00
  AtlasBurningCrusade, vv1.44.00
  AtlasCataclysm, vv1.44.00
  AtlasClassicWoW, vv1.44.00
  AtlasClassOrderHalls, vv1.44.00
  AtlasDungeonLocs, vv1.44.00
  AtlasLegion, vv1.44.00
  AtlasMistsofPandaria, vv1.44.00
  AtlasOutdoorRaids, vv1.44.00
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.00
  AtlasWarlordsofDraenor, vv1.44.00
  AtlasWorldEvents, vv3.24
  AtlasWrathoftheLichKing, vv1.44.00
  AtlasMajorCitiesEnhanced, vv1.16
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucScanData, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  BadBoy, vv8.0.7
  BadBoyGuilded, vv8.0.0
  BadBoyIgnore, vv8.0.0
  BadPet, vv1.0.12
  BagBrother, v
  Bagnon, v8.0.2
  Bartender4, v4.8.1
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  BugSack, vv8.0.2
  CanIMogIt, v8.0.0v1.11
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr42
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr37
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr45
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.0.4
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  Decliner, v8.0.1.180722.1
  Decursive, v2.7.6.1
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  FBOutfitDisplayFrame, v1.9.1
  FBTitan, v1.0.15
  FBTrackingFrame, v1.9
  FishingBuddy, v1.9.13
  FlightMapEnhanced, v3.0.14
  GarrisonCommanderBroker, v2.19.0 1.1.0
  GatherMate2, v1.43
  GatherMateSharing, vv1.11
  GFWDiggerAid, v8.0
  GFWFactionFriend, v8.0.1
  GFWFeedOMatic, v8.0
  GFWHoverTips, v8.0
  GFWScrollMaker, v8.0
  GFWXPVisualizer, v8.0
  GFWZippyLighter, v8.0
  gmFonts, v801-2018071801
  GTFO, v4.46.2
  HandyNotes, vv1.5.3
  HandyNotesBrokenShore, vv1.29
  HandyNotesDraenorTreasures, v1.21
  HandyNotesFieldPhotographer, v8.0.0.0
  HandyNotesHigherLearning, v8.0.0.0
  HandyNotesLegionClassOrderHalls, vv1.29
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesWellRead, v8.0.0.0
  Healium, v
  iFriends, v8.0.4
  iGuild, v8.0.4
  iLib, v1.0
  Informant, v7.7.6000 (SwimmingSeadragon)
  iSocial, v8.0.3
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesElite, vv2.4
  LightHeaded, vv80000-1.1.0-431924f
  LightHeadedDataD, vwowi:revision
  LightHeadedDataE, vwowi:revision
  LightHeadedDataQIDNames, vwowi:revision
  MacroToolkit, vv7.3.0.2
  MacroToolkitMacroBox, vv7.2.0.0
  MacroToolkitIcons, v7.2.0.0
  MailCommander, v0.9.8 80000
  MasterPlanA, vA
  MicroDeclineDuel, vv8.0
  MogIt, v3.8.10
  MogItArtifact, v3.8.10
  MogItCloth, v3.8.10
  MogItLeather, v3.8.10
  MogItMail, v3.8.10
  MogItOneHanded, v3.8.10
  MogItOther, v3.8.10
  MogItPlate, v3.8.10
  MogItRanged, v3.8.10
  MogItTwoHanded, v3.8.10
  NOP, v09.10 14.08.2018
  NPCScan, v8.0.1.8
  Omen, v3.2.0
  Outfitter, v5.20.3
  Overachiever, v1.0.3
  OverachieverCache, v1.0.3
  OverachieverTabs, v1.0.3
  OverachieverTrade, v1.0.3
  Pawn, v2.2.27
  Prat30, vr1178      
  Prat30Libraries, v
  RETabBinder, v1.4.0
  sct, v8.1
  sctd, v7.1
  SharedMedia, v8.0.2
  SharedMediaClassicalFonts, v7.3-release1
  SharedMediaAdditionalFonts, v1.0.26
  SilverDragon, vv4.0.13
  SilverDragonBattleForAzeroth, vv4.0.13
  SilverDragonBurningCrusade, vv4.0.13
  SilverDragonCataclysm, vv4.0.13
  SilverDragonLegion, vv4.0.13
  SilverDragonMists, vv4.0.13
  SilverDragonVanilla, vv4.0.13
  SilverDragonWarlords, vv4.0.13
  SilverDragonWrath, vv4.0.13
  Skillet, v4.04
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  SpartanUI, v4.6.9
  SpartanUIArtwork, v4.6.9
  SpartanUIFilmEffects, v4.6.9
  SpartanUIPartyFrames, v4.6.9
  SpartanUIPlayerFrames, v4.6.9
  SpartanUIRaidFrames, v4.6.9
  SpartanUISpinCam, v4.6.9
  SpartanUIStyleFel, v4.6.9
  SpartanUIStyleMinimal, v4.6.9
  SpartanUIStyleTransparent, v4.6.9
  SpartanUIStyleWar, v4.6.9
  Stubby, v7.7.6000 (SwimmingSeadragon)
  TabardMaster, v125
  TipTac, v18.08.20
  TipTacItemRef, v18.08.12
  TipTacTalents, v18.07.30
  Titan, v5.14.4.80000
  TitanBag, v5.14.4.80000
  TitanClan, v39
  TitanClock, v5.14.4.80000
  TitanGold, v5.14.4.80000
  TitanLocation, v5.14.4.80000
  TitanLootType, v5.14.4.80000
  TitanPerformance, v5.14.4.80000
  TitanRepair, v5.14.4.80000
  TitanRestPlus, v8.0.0.0
  TitanSocial, v8.0.1
  TitanVolume, v5.14.4.80000
  TitanXP, v5.14.4.80000
  TomTom, vv80001-1.0.2
  TomTomPing, v1.3 r038
  totalRP3, v1.4.4
  totalRP3Data, v
  totalRP3Extended, v1.2.0
  totalRP3ExtendedImpExport, v1.2.0
  totalRP3ExtendedTools, v1.2.0
  totalRP3KuiNameplates, v1.4.0
  TradeSkillMaster, vv4.1.1
  TradeSkillMasterAppHelper, vv4.0
  TRP3CurrentlyFrame, v1.6
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=14ce)

=============================================

**Comment by funkydude** [comment] 2018-08-23 01:55
Duplicate of #95

**Closed by funkydude** 2018-08-23 01:55 UTC
