### ISSUE TITLE
Lua errors after v8.0.11 update

### ISSUE THREAD

**Issue by mLgz0rn** [funkydude/BadBoy#103] opened 2018-10-23 18:38 UTC
Been getting lua errors since I updated to the new version.

https://pastebin.com/gPDNCgdi
https://pastebin.com/ufnPrz3u

**Comment by funkydude** [comment] 2018-10-23 20:00
Duplicate of https://github.com/funkydude/BadBoy/issues/95

**Closed by funkydude** 2018-10-23 20:00 UTC
