### ISSUE TITLE
Error when reloading ui or logging in and a chat window was open

### ISSUE THREAD

**Issue by TXKelemvor** [funkydude/BadBoy#91] opened 2018-04-06 00:33 UTC
1x BadBoy: Unexpected GUID requested by an addon: Tyruson
BadBoy_Levels\BadBoy_Levels-v7.3.0.lua:196: in function `filterFunc'
ElvUI\Modules\chat\chat-Chat.lua:1170: in function `ChatFrame_MessageEventHandler'
ElvUI\Modules\chat\chat-Chat.lua:1916: in function `DisplayChatHistory'
ElvUI\Modules\chat\chat-Chat.lua:2299: in function `Initialize'
ElvUI\Modules\chat\chat-Chat.lua:2392: in function <ElvUI\Modules\chat\chat.lua:2391>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:155: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
ElvUI\core\core.lua:1383: in function `InitializeModules'
ElvUI\core\core.lua:1572: in function `Initialize'
ElvUI\init.lua:140: in function <ElvUI\init.lua:139>

Locals:
nil

**Comment by funkydude** [comment] 2018-04-07 03:28
Duplicate of https://github.com/funkydude/BadBoy/issues/90

**Closed by funkydude** 2018-04-07 03:28 UTC
