### ISSUE TITLE
WOTLK LUA error - ReportPlayer

### ISSUE THREAD

**Issue by Nillx** [funkydude/BadBoy#155] opened 2022-10-17 17:24 UTC
Getting this error when trying to report a spam (clicking the shield icon)

```
1x BadBoy\BadBoy_Classic.lua:276: attempt to call upvalue 'ReportPlayer' (a nil value)
[string "@BadBoy\BadBoy_Classic.lua"]:276: in function <BadBoy\BadBoy_Classic.lua:254>

Locals:
self = <unnamed> {
 0 = <userdata>
}
systemMsg = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = ChatFrame1 {
 }
 4 = AceEvent30Frame {
 }
}
infoMsg = <table> {
 1 = UIErrorsFrame {
 }
 2 = <unnamed> {
 }
 3 = AceEvent30Frame {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Player-4465-03054AE6 = <table> {
 }
}
(for control) = "Player-4465-03054AE6"
k = "Player-4465-03054AE6"
v = <table> {
 GetWhoIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:154
 chatLineID = 12240
 SetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:119
 SetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:59
 IsBattleNetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:75
 IsCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:166
 GetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:115
 GetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:103
 SetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:107
 SetCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:170
 IsGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:71
 GetBattleNetID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:142
 IsChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:99
 IsBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:111
 Clear = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:181
 IsValid = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:63
 IsWhoIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:150
 IsVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:125
 SetWhoIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:146
 IsUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:87
 SetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:83
 SetBattleNetID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:133
 IsCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:176
 GetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:79
 ClearAndSetField = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:196
 GetUnit = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:91
 GetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:129
 SetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:95
 IsBattleNetID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:138
 SetCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:158
}
go = true
pass = true
(*temporary) = nil
(*temporary) = "spam"
(*temporary) = <table> {
 GetWhoIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:154
 chatLineID = 12240
 SetVoiceID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:119
 SetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:59
 IsBattleNetGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:75
 IsCommunityData = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:166
 GetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:115
 GetChatLineID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:103
 SetBattlefieldScoreIndex = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:107
 SetCommunityInvitation = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:170
 IsGUID = <function> defined @FrameXML\ObjectAPI\PlayerLocation.lua:71
 GetBattleNetID = <function> defined @FrameXML\ObjectAPI\Play
```

**Comment by funkydude** [comment] 2022-10-19 00:34
Duplicate of #153

**Closed by funkydude** 2022-10-19 00:34 UTC
Labels: wotlkc
