### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [funkydude/BadBoy#110] opened 2019-04-27 20:26 UTC
Count: 1
Message: ..\AddOns\BadBoy\BadBoy.lua line 284:
   bad argument #1 to 'CanReportPlayer' (Usage: local canReport = C_ReportSystem.CanReportPlayer(playerLocation))
Debug:
   [C]: ?
   [C]: ?
   BadBoy\BadBoy.lua:284:
      BadBoy\BadBoy.lua:262
Locals:

**Comment by funkydude** [comment] 2019-04-28 22:03
Duplicate of #108

**Closed by funkydude** 2019-04-28 22:03 UTC
